#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

# register:
#   path: /register
#   methods: POST

api:
  path: /api
  controller: App\Controller\AuthController::api

login_check:
  path:     /login_check
  methods:  [POST]